backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow


media_folder: static/assets
public_folder: /assets
collections:
  - name: candy
    label: Candy
    folder: candy
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: number, label: Number, widget: number }
