backend:
  name: git-gateway
  branch: master


media_folder: static/images
public_folder: /
collections:
  - name: candy
    label: Candy
    folder: candy
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: number, label: Number, widget: number }
      - name: images
        label: Pictures
        widget: list
        fields:
          - { name: image, label: Image, widget: image }
